-- MySQL Script generated by MySQL Workbench
-- jeu. 27 janv. 2022 16:51:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mabase
-- -----------------------------------------------------
-- une base de données pour la facturation d'une entreprise

-- -----------------------------------------------------
-- Schema mabase
--
-- une base de données pour la facturation d'une entreprise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mabase` DEFAULT CHARACTER SET utf8 ;
USE `mabase` ;

-- -----------------------------------------------------
-- Table `mabase`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mabase`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `nom_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mabase`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mabase`.`utilisateurs` (
  `idutilisateurs` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `idroles` INT NOT NULL,
  PRIMARY KEY (`idutilisateurs`),
  INDEX `fk_utilisateurs_1_idx` (`idroles` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateurs_1`
    FOREIGN KEY (`idroles`)
    REFERENCES `mabase`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'table contenant mes utilisateurs';


-- -----------------------------------------------------
-- Table `mabase`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mabase`.`clients` (
  `idclients` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `Tel` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(50) NULL,
  `idutilisateurs` INT NOT NULL,
  PRIMARY KEY (`idclients`),
  INDEX `fk_clients_1_idx` (`idutilisateurs` ASC) VISIBLE,
  CONSTRAINT `fk_clients_1`
    FOREIGN KEY (`idutilisateurs`)
    REFERENCES `mabase`.`utilisateurs` (`idutilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mabase`.`references`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mabase`.`references` (
  `idreferences` INT NOT NULL AUTO_INCREMENT,
  `code_ref` INT UNSIGNED NULL,
  PRIMARY KEY (`idreferences`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mabase`.`factures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mabase`.`factures` (
  `idfactures` INT NOT NULL AUTO_INCREMENT,
  `objet` VARCHAR(45) NOT NULL,
  `idutilisateurs` INT NOT NULL,
  `idclients` INT NOT NULL,
  `quantité` INT NOT NULL,
  `designation` VARCHAR(100) NOT NULL,
  `prix_unitaire` INT NOT NULL,
  `reference` INT NOT NULL,
  PRIMARY KEY (`idfactures`),
  INDEX `fk_factures_2_idx` (`idutilisateurs` ASC) VISIBLE,
  INDEX `fk_factures_3_idx` (`reference` ASC) VISIBLE,
  CONSTRAINT `fk_factures_1`
    FOREIGN KEY ()
    REFERENCES `mabase`.`clients` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factures_2`
    FOREIGN KEY (`idutilisateurs`)
    REFERENCES `mabase`.`utilisateurs` (`idutilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factures_3`
    FOREIGN KEY (`reference`)
    REFERENCES `mabase`.`references` (`idreferences`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
